-- Catalogo inicial de tecnologias.
-- O slug segue exatamente a regra de Slugifier.java: minusculo, sem acento,
-- nao alfanumerico vira "-", "#" vira "sharp" e "+" vira "plus".

INSERT INTO technologies (name, slug, category, created_at) VALUES
    ('Java', 'java', 'LANGUAGE', now()),
    ('Kotlin', 'kotlin', 'LANGUAGE', now()),
    ('JavaScript', 'javascript', 'LANGUAGE', now()),
    ('TypeScript', 'typescript', 'LANGUAGE', now()),
    ('Python', 'python', 'LANGUAGE', now()),
    ('Go', 'go', 'LANGUAGE', now()),
    ('C', 'c', 'LANGUAGE', now()),
    ('C#', 'csharp', 'LANGUAGE', now()),
    ('C++', 'cplusplus', 'LANGUAGE', now()),
    ('PHP', 'php', 'LANGUAGE', now()),
    ('Ruby', 'ruby', 'LANGUAGE', now()),
    ('Rust', 'rust', 'LANGUAGE', now()),
    ('Swift', 'swift', 'LANGUAGE', now()),
    ('Dart', 'dart', 'LANGUAGE', now()),
    ('HTML', 'html', 'LANGUAGE', now()),
    ('CSS', 'css', 'LANGUAGE', now()),
    ('SQL', 'sql', 'LANGUAGE', now()),
    ('Shell', 'shell', 'TOOL', now()),

    ('Spring Boot', 'spring-boot', 'FRAMEWORK', now()),
    ('Spring Security', 'spring-security', 'FRAMEWORK', now()),
    ('Spring Data JPA', 'spring-data-jpa', 'FRAMEWORK', now()),
    ('Hibernate', 'hibernate', 'FRAMEWORK', now()),
    ('Quarkus', 'quarkus', 'FRAMEWORK', now()),
    ('Node.js', 'node-js', 'FRAMEWORK', now()),
    ('Express', 'express', 'FRAMEWORK', now()),
    ('React', 'react', 'FRAMEWORK', now()),
    ('Vue', 'vue', 'FRAMEWORK', now()),
    ('Angular', 'angular', 'FRAMEWORK', now()),
    ('Next.js', 'next-js', 'FRAMEWORK', now()),
    ('Django', 'django', 'FRAMEWORK', now()),
    ('Flask', 'flask', 'FRAMEWORK', now()),
    ('FastAPI', 'fastapi', 'FRAMEWORK', now()),
    ('Laravel', 'laravel', 'FRAMEWORK', now()),
    ('Flutter', 'flutter', 'FRAMEWORK', now()),

    ('PostgreSQL', 'postgresql', 'DATABASE', now()),
    ('MySQL', 'mysql', 'DATABASE', now()),
    ('MongoDB', 'mongodb', 'DATABASE', now()),
    ('Redis', 'redis', 'DATABASE', now()),
    ('SQLite', 'sqlite', 'DATABASE', now()),
    ('H2', 'h2', 'DATABASE', now()),

    ('Docker', 'docker', 'TOOL', now()),
    ('Docker Compose', 'docker-compose', 'TOOL', now()),
    ('Maven', 'maven', 'TOOL', now()),
    ('Gradle', 'gradle', 'TOOL', now()),
    ('Git', 'git', 'TOOL', now()),
    ('Make', 'make', 'TOOL', now()),
    ('Swagger', 'swagger', 'TOOL', now()),
    ('Nginx', 'nginx', 'TOOL', now()),
    ('pip', 'pip', 'TOOL', now()),
    ('Poetry', 'poetry', 'TOOL', now()),
    ('Composer', 'composer', 'TOOL', now()),
    ('Bundler', 'bundler', 'TOOL', now()),
    ('Cargo', 'cargo', 'TOOL', now()),
    ('Go Modules', 'go-modules', 'TOOL', now()),

    ('JUnit', 'junit', 'TESTING', now()),
    ('Mockito', 'mockito', 'TESTING', now()),
    ('Testcontainers', 'testcontainers', 'TESTING', now()),
    ('Jest', 'jest', 'TESTING', now()),
    ('PyTest', 'pytest', 'TESTING', now()),
    ('Playwright', 'playwright', 'TESTING', now()),
    ('Cypress', 'cypress', 'TESTING', now()),

    ('AWS', 'aws', 'CLOUD', now()),
    ('GitHub Actions', 'github-actions', 'CLOUD', now()),
    ('Vercel', 'vercel', 'CLOUD', now()),
    ('Render', 'render', 'CLOUD', now()),
    ('Railway', 'railway', 'CLOUD', now()),
    ('Kubernetes', 'kubernetes', 'CLOUD', now()),
    ('Terraform', 'terraform', 'CLOUD', now()),
    ('Heroku', 'heroku', 'CLOUD', now());
